trigger:
  - develop

variables:
  buildConfiguration: 'Release'
  targetPool: AvanadeAcademy

pool: $(targetPool)

steps:
- script: dotnet restore
  displayName: Ripristino dei pacchetti NuGet
  enabled: true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build dell'intera soluzione
  enabled: true

- script: |
    cd Avanade.Amazon.Api.Tests
    dotnet test --configuration $(buildConfiguration) --logger "trx;LogFileName=testresults.trx"
  displayName: Lancio dei test
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'